apiVersion: apps/v1
kind: Deployment
metadata:

  labels:
    app: flaskdemo
  name: flaskdemo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaskdemo
  template:
    metadata:

      labels:
        app: flaskdemo
    spec:
      containers:
      - image: meets0ni/test:2
        name: flaskdemo
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    app: lb-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: flaskdemo
